# Generated by Django 3.1.2 on 2020-10-26 21:30

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('message_credits', models.IntegerField(default=100)),
                ('height', models.IntegerField()),
                ('sex_drive', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('gender', models.CharField(max_length=200)),
                ('body_type', models.CharField(choices=[('Slim', 'Slim and Slender'), ('Fit', 'Athletic and Fit'), ('Average', 'Average'), ('Muscular', 'Muscular'), ('Curvy', 'Curvy'), ('Extra', 'A Few Extra Pounds'), ('Heavy', 'Heavyset')], max_length=200)),
                ('relationship_status', models.CharField(choices=[('single', 'Never Married'), ('married', 'Married'), ('seperated', 'Currently Seperated'), ('divorced', 'Divorced'), ('widow', 'Widow or Widower')], max_length=200)),
                ('education', models.CharField(choices=[('HS', 'High School'), ('college', 'Some College'), ('associate', 'Associates degree'), ('bachelor', 'Bachelors degree'), ('graduate', 'Graduate degree'), ('phd', 'PhD or Post Doctoral')], max_length=200)),
                ('religion', models.CharField(choices=[('christian', 'Christian'), ('islam', 'Islam'), ('buddist', 'Buddist'), ('hindu', 'Hindu'), ('jewish', 'Jewish'), ('agnostic', 'Agnostic'), ('atheist', 'Atheist'), ('other', 'Other')], max_length=200)),
                ('race', models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('hispanic', 'Hispanic'), ('asian', 'Asian'), ('native', 'Native American'), ('mideast', 'Middle Eastern'), ('pacific', 'Pacific Islander'), ('indian', 'East Indian'), ('other', 'Other')], max_length=200)),
                ('interests', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('tv', 'Watching TV'), ('concert', 'Concerts'), ('cook', 'Cooking'), ('dance', 'Dancing'), ('dine', 'Dining Out'), ('games', 'Video Games'), ('garden', 'Gardening'), ('hike', 'Hiking'), ('movies', 'Movies'), ('art', 'Art'), ('music', 'Music'), ('nightlife', 'Nightlife'), ('playSport', 'Playing Sports'), ('watchSport', 'Watching Sports'), ('reading', 'Reading'), ('religion', 'Religion'), ('shopping', 'Shopping'), ('travel', 'Travel'), ('volunteering', 'Volunteering'), ('gym', 'Working Out')], max_length=200), size=None)),
                ('description', models.TextField()),
                ('has_kids', models.BooleanField()),
                ('wants_kids', models.BooleanField()),
                ('smokes', models.BooleanField()),
                ('drinks', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
