# Generated by Django 3.1.2 on 2020-10-29 15:02

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(verbose_name='Link to a picture of you')),
                ('message_credits', models.IntegerField(default=100)),
                ('height', models.IntegerField(null=True, verbose_name='Height in centimeters')),
                ('sex_drive', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('gender', models.CharField(max_length=200, null=True)),
                ('body_type', models.CharField(choices=[('Slim', 'Slim and Slender'), ('Fit', 'Athletic and Fit'), ('Average', 'Average'), ('Muscular', 'Muscular'), ('Curvy', 'Curvy'), ('Extra', 'A Few Extra Pounds'), ('Heavy', 'Heavyset')], max_length=200, null=True)),
                ('relationship_status', models.CharField(choices=[('single', 'Never Married'), ('married', 'Married'), ('seperated', 'Currently Seperated'), ('divorced', 'Divorced'), ('widow', 'Widow or Widower')], max_length=200, null=True)),
                ('education', models.CharField(choices=[('HS', 'High School'), ('college', 'Some College'), ('associate', 'Associates degree'), ('bachelor', 'Bachelors degree'), ('graduate', 'Graduate degree'), ('phd', 'PhD or Post Doctoral')], max_length=200, null=True)),
                ('religion', models.CharField(choices=[('christian', 'Christian'), ('islam', 'Islam'), ('buddist', 'Buddist'), ('hindu', 'Hindu'), ('jewish', 'Jewish'), ('agnostic', 'Agnostic'), ('atheist', 'Atheist'), ('other', 'Other')], max_length=200, null=True)),
                ('race', models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('hispanic', 'Hispanic'), ('asian', 'Asian'), ('native', 'Native American'), ('mideast', 'Middle Eastern'), ('pacific', 'Pacific Islander'), ('indian', 'East Indian'), ('other', 'Other')], max_length=200, null=True)),
                ('interests', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('tv', 'Watching TV'), ('concert', 'Concerts'), ('cook', 'Cooking'), ('dance', 'Dancing'), ('dine', 'Dining Out'), ('games', 'Video Games'), ('garden', 'Gardening'), ('hike', 'Hiking'), ('movies', 'Movies'), ('art', 'Art'), ('music', 'Music'), ('nightlife', 'Nightlife'), ('playSport', 'Playing Sports'), ('watchSport', 'Watching Sports'), ('reading', 'Reading'), ('religion', 'Religion'), ('shopping', 'Shopping'), ('travel', 'Travel'), ('volunteering', 'Volunteering'), ('gym', 'Working Out')], max_length=200), default=list, size=None)),
                ('description', models.TextField(null=True, verbose_name='Describe yourself in your own words')),
                ('has_kids', models.BooleanField(default=False, verbose_name='I currently have children')),
                ('wants_kids', models.BooleanField(default=False, verbose_name='I want children in the future')),
                ('smokes', models.BooleanField(default=False, verbose_name='I use tobacco')),
                ('drinks', models.BooleanField(default=False, verbose_name='I drink alcohol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_height', models.IntegerField()),
                ('min_height', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('min_sex_drive', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_sex_drive', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('genders', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('body_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Slim', 'Slim and Slender'), ('Fit', 'Athletic and Fit'), ('Average', 'Average'), ('Muscular', 'Muscular'), ('Curvy', 'Curvy'), ('Extra', 'A Few Extra Pounds'), ('Heavy', 'Heavyset')], max_length=200), size=None)),
                ('relationship_status', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('single', 'Never Married'), ('married', 'Married'), ('seperated', 'Currently Seperated'), ('divorced', 'Divorced'), ('widow', 'Widow or Widower')], max_length=200), size=None)),
                ('education', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('HS', 'High School'), ('college', 'Some College'), ('associate', 'Associates degree'), ('bachelor', 'Bachelors degree'), ('graduate', 'Graduate degree'), ('phd', 'PhD or Post Doctoral')], max_length=200), size=None)),
                ('religion', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('christian', 'Christian'), ('islam', 'Islam'), ('buddist', 'Buddist'), ('hindu', 'Hindu'), ('jewish', 'Jewish'), ('agnostic', 'Agnostic'), ('atheist', 'Atheist'), ('other', 'Other')], max_length=200), size=None)),
                ('race', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('hispanic', 'Hispanic'), ('asian', 'Asian'), ('native', 'Native American'), ('mideast', 'Middle Eastern'), ('pacific', 'Pacific Islander'), ('indian', 'East Indian'), ('other', 'Other')], max_length=200), size=None)),
                ('smoke', models.BooleanField()),
                ('never_smoke', models.BooleanField()),
                ('drink', models.BooleanField()),
                ('never_drink', models.BooleanField()),
                ('has_kids', models.BooleanField()),
                ('has_no_kids', models.BooleanField()),
                ('wants_kids', models.BooleanField()),
                ('never_wants_kids', models.BooleanField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.profile')),
            ],
        ),
    ]
