# Generated by Django 3.1.2 on 2020-10-26 22:13

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_height', models.IntegerField()),
                ('min_height', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('min_sex_drive', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_sex_drive', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('genders', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('body_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Slim', 'Slim and Slender'), ('Fit', 'Athletic and Fit'), ('Average', 'Average'), ('Muscular', 'Muscular'), ('Curvy', 'Curvy'), ('Extra', 'A Few Extra Pounds'), ('Heavy', 'Heavyset')], max_length=200), size=None)),
                ('relationship_status', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('single', 'Never Married'), ('married', 'Married'), ('seperated', 'Currently Seperated'), ('divorced', 'Divorced'), ('widow', 'Widow or Widower')], max_length=200), size=None)),
                ('education', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('HS', 'High School'), ('college', 'Some College'), ('associate', 'Associates degree'), ('bachelor', 'Bachelors degree'), ('graduate', 'Graduate degree'), ('phd', 'PhD or Post Doctoral')], max_length=200), size=None)),
                ('religion', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('christian', 'Christian'), ('islam', 'Islam'), ('buddist', 'Buddist'), ('hindu', 'Hindu'), ('jewish', 'Jewish'), ('agnostic', 'Agnostic'), ('atheist', 'Atheist'), ('other', 'Other')], max_length=200), size=None)),
                ('race', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('hispanic', 'Hispanic'), ('asian', 'Asian'), ('native', 'Native American'), ('mideast', 'Middle Eastern'), ('pacific', 'Pacific Islander'), ('indian', 'East Indian'), ('other', 'Other')], max_length=200), size=None)),
                ('smoke', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), size=None)),
                ('drink', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), size=None)),
                ('has_kids', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), size=None)),
                ('wants_kids', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), size=None)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.profile')),
            ],
        ),
    ]
