# Generated by Django 3.1.2 on 2020-10-30 14:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='body_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Slim and Slender', 'Slim and Slender'), ('Athletic and Fit', 'Athletic and Fit'), ('Average', 'Average'), ('Muscular', 'Muscular'), ('Curvy', 'Curvy'), ('A Few Extra Pounds', 'A Few Extra Pounds'), ('Heavyset', 'Heavyset')], max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='drink',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='education',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('High School', 'High School'), ('Some College', 'Some College'), ('Associates degree', 'Associates degree'), ('Bachelors degree', 'Bachelors degree'), ('Graduate degree', 'Graduate degree'), ('PhD or Post Doctoral', 'PhD or Post Doctoral')], max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='has_kids',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='has_no_kids',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='never_drink',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='never_smoke',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='never_wants_kids',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='race',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Hispanic', 'Hispanic'), ('Asian', 'Asian'), ('Native', 'Native American'), ('Middle Eastern', 'Middle Eastern'), ('Pacific Islander', 'Pacific Islander'), ('East Indian', 'East Indian'), ('Other', 'Other')], max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='relationship_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Never Married', 'Never Married'), ('Married', 'Married'), ('Currently Seperated', 'Currently Seperated'), ('Divorced', 'Divorced'), ('Widow or Widower', 'Widow or Widower')], max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='religion',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Christian', 'Christian'), ('Islam', 'Islam'), ('Buddist', 'Buddist'), ('Hindu', 'Hindu'), ('Jewish', 'Jewish'), ('Agnostic', 'Agnostic'), ('Atheist', 'Atheist'), ('Other', 'Other')], max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='smoke',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='wants_kids',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='body_type',
            field=models.CharField(choices=[('Slim and Slender', 'Slim and Slender'), ('Athletic and Fit', 'Athletic and Fit'), ('Average', 'Average'), ('Muscular', 'Muscular'), ('Curvy', 'Curvy'), ('A Few Extra Pounds', 'A Few Extra Pounds'), ('Heavyset', 'Heavyset')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(choices=[('High School', 'High School'), ('Some College', 'Some College'), ('Associates degree', 'Associates degree'), ('Bachelors degree', 'Bachelors degree'), ('Graduate degree', 'Graduate degree'), ('PhD or Post Doctoral', 'PhD or Post Doctoral')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Watching TV', 'Watching TV'), ('Concerts', 'Concerts'), ('Cooking', 'Cooking'), ('Dancing', 'Dancing'), ('Dining Out', 'Dining Out'), ('Video Games', 'Video Games'), ('Gardening', 'Gardening'), ('Hiking', 'Hiking'), ('Movies', 'Movies'), ('Art', 'Art'), ('Music', 'Music'), ('Nightlife', 'Nightlife'), ('Playing Sports', 'Playing Sports'), ('Watching Sports', 'Watching Sports'), ('Reading', 'Reading'), ('Religion', 'Religion'), ('Shopping', 'Shopping'), ('Travel', 'Travel'), ('Volunteering', 'Volunteering'), ('Working Out', 'Working Out')], max_length=200), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='race',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Hispanic', 'Hispanic'), ('Asian', 'Asian'), ('Native', 'Native American'), ('Middle Eastern', 'Middle Eastern'), ('Pacific Islander', 'Pacific Islander'), ('East Indian', 'East Indian'), ('Other', 'Other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship_status',
            field=models.CharField(choices=[('Never Married', 'Never Married'), ('Married', 'Married'), ('Currently Seperated', 'Currently Seperated'), ('Divorced', 'Divorced'), ('Widow or Widower', 'Widow or Widower')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.CharField(choices=[('Christian', 'Christian'), ('Islam', 'Islam'), ('Buddist', 'Buddist'), ('Hindu', 'Hindu'), ('Jewish', 'Jewish'), ('Agnostic', 'Agnostic'), ('Atheist', 'Atheist'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
