# Generated by Django 3.1.2 on 2020-10-30 15:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201030_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Watching TV', 'Watching TV'), ('Concerts', 'Concerts'), ('Cooking', 'Cooking'), ('Dancing', 'Dancing'), ('Dining Out', 'Dining Out'), ('Video Games', 'Video Games'), ('Gardening', 'Gardening'), ('Hiking', 'Hiking'), ('Movies', 'Movies'), ('Art', 'Art'), ('Music', 'Music'), ('Nightlife', 'Nightlife'), ('Playing Sports', 'Playing Sports'), ('Watching Sports', 'Watching Sports'), ('Reading', 'Reading'), ('Religion', 'Religion'), ('Shopping', 'Shopping'), ('Travel', 'Travel'), ('Volunteering', 'Volunteering'), ('Working Out', 'Working Out'), ('Camping', 'Camping'), ('Board Games', 'Board Games')], max_length=200), default=list, size=None),
        ),
    ]
