# Generated by Django 3.1.2 on 2020-10-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201030_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
