# Generated by Django 3.1.2 on 2020-10-27 20:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201027_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('tv', 'Watching TV'), ('concert', 'Concerts'), ('cook', 'Cooking'), ('dance', 'Dancing'), ('dine', 'Dining Out'), ('games', 'Video Games'), ('garden', 'Gardening'), ('hike', 'Hiking'), ('movies', 'Movies'), ('art', 'Art'), ('music', 'Music'), ('nightlife', 'Nightlife'), ('playSport', 'Playing Sports'), ('watchSport', 'Watching Sports'), ('reading', 'Reading'), ('religion', 'Religion'), ('shopping', 'Shopping'), ('travel', 'Travel'), ('volunteering', 'Volunteering'), ('gym', 'Working Out')], max_length=200), blank=True, size=None),
        ),
    ]
