# Generated by Django 3.1.2 on 2020-11-01 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_message_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date_created']},
        ),
    ]
