# Generated by Django 3.1.2 on 2020-11-20 22:13

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20201101_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='body_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Slim and Slender', 'Slim and Slender'), ('Athletic and Fit', 'Athletic and Fit'), ('Average', 'Average'), ('Muscular', 'Muscular'), ('Curvy', 'Curvy'), ('A Few Extra Pounds', 'A Few Extra Pounds'), ('Heavyset', 'Heavyset')], max_length=200, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='education',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('High School', 'High School'), ('Some College', 'Some College'), ('Associates degree', 'Associates degree'), ('Bachelors degree', 'Bachelors degree'), ('Graduate degree', 'Graduate degree'), ('PhD or Post Doctoral', 'PhD or Post Doctoral')], max_length=200, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='genders',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='max_height',
            field=models.IntegerField(default=244),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='max_sex_drive',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='min_height',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='min_sex_drive',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='race',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Hispanic', 'Hispanic'), ('Asian', 'Asian'), ('Native', 'Native American'), ('Middle Eastern', 'Middle Eastern'), ('Pacific Islander', 'Pacific Islander'), ('East Indian', 'East Indian'), ('Other', 'Other')], max_length=200, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='relationship_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Never Married', 'Never Married'), ('Married', 'Married'), ('Currently Seperated', 'Currently Seperated'), ('Divorced', 'Divorced'), ('Widow or Widower', 'Widow or Widower')], max_length=200, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='religion',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Christian', 'Christian'), ('Islam', 'Islam'), ('Buddist', 'Buddist'), ('Hindu', 'Hindu'), ('Jewish', 'Jewish'), ('Agnostic', 'Agnostic'), ('Atheist', 'Atheist'), ('Other', 'Other')], max_length=200, null=True), size=None),
        ),
    ]
