# Generated by Django 3.1.2 on 2020-11-20 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20201120_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='max_height',
            field=models.IntegerField(default=244, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='max_sex_drive',
            field=models.IntegerField(default=100, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='min_height',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='min_sex_drive',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
